"""empty message

Revision ID: 2c53b23b2184
Revises: b4234e411cec
Create Date: 2025-02-02 18:08:18.364518

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c53b23b2184"
down_revision: Union[str, None] = "b4234e411cec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "equipment", ["name"])
    op.create_unique_constraint(None, "factory", ["name"])
    op.create_unique_constraint(None, "site", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "site", type_="unique")
    op.drop_constraint(None, "factory", type_="unique")
    op.drop_constraint(None, "equipment", type_="unique")
    # ### end Alembic commands ###
