"""empty message

Revision ID: 7909b49403e5
Revises: 2c53b23b2184
Create Date: 2025-02-02 19:00:06.599827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7909b49403e5"
down_revision: Union[str, None] = "2c53b23b2184"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        None, "site_equipment", ["site_id", "equipment_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "site_equipment", type_="unique")
    # ### end Alembic commands ###
