version: '3.10'
name: test_api

services:
  db_test_api:
    image: postgres:16.1-alpine
    container_name: db_test_api
    ports:
      - "5432:5432"
    volumes:
      - db_test_api:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - test_api_web

  test_api:
    build:
      context: ../src
    container_name: test_api
    volumes:
      - ../src:/src
    env_file:
      - .env
    networks:
      - test_api_web
    depends_on:
      - db_test_api
    ports:
      - "4000:4000"

networks:
  test_api_web:
    driver: bridge

volumes:
  db_test_api: